### ISSUE TITLE
Google Translate gives error

### ISSUE THREAD

**Issue by indulanka** [zhw2590582/SubPlayer#13]
Hi Harvey,
Please be kind enough to fix the Google Translate error on this repo with the guidelines given on the following link;

https://objectcomputing.com/resources/publications/sett/september-2018-web-translate-javascript-library

Thanks and Regards,
Indunil Sanjeewa

**Comment by zhw2590582** [comment]
Hello, thanks for your suggestions, but as your link says "NO FREE LUNCH", if you use this method, when a certain number of translations are reached, it will be consumed. As an open source project, I do n’t want to do this because I do n’t use the project for profit, let alone spend money on translation services.
