### ISSUE TITLE
new functions

### ISSUE THREAD

**Issue by ahmad-ali14** [zhw2590582/SubPlayer#16]
hi zhw2590582, I have added the following functionalities to your project :
1- some styling changes.
2- you can now change the end and start of the subtitle from the subtitles box as well as the time meter at the bottom.
3- you have a right menu option to copy subtitle text directly to the clipboard.
4- you can select multiple subtitles and do functions on them.
5- if you select one or more subtitles the vedio will loop from the start of the first select sub until the finish of the last sub, and will never pass until you choose that, so this will give you more power to work on a single sub.
6- dynamically choose the shifting offset.
7-  more uploading option like from a url or Google drive.

if you interested in adding those functions please tell me so I can make a pull request with the changes.

cheers
Ahmad

**Comment by zhw2590582** [comment]
Thank you very much for your suggestions. At present, the code of the two components of the editor is messy `Metronome.js` and` Block.js`. I need time to optimize them, but the other components are easy to modify.

1-I want to know which elements need to be modified
2-I do n’t think it ’s common to adjust the start time and end time of the subtitles on the right, because usually people do n’t know the exact time, so I forbid to modify the time directly, but drag and drop the slider directly through the bottom will be more convenient and intuitive.
3-Right-click copy function sounds good
4-Multi-select subtitles are also good, but the code changes will be great, I do n’t know if it ’s worth it
5-This suggestion is awesome and can save a lot of editing time
6-I don't quite understand this
7-The editor itself supports getting subtitles and videos from url, but it is not perfect, so I temporarily disabled it, or I can enable it now
